name: bottom_bar_with_sheet
description: This package help you to create bottom bar with FloatingActionButton which buld BottomSheet widget on every page.
version: 0.5.5
author: youngfrezyx@gmail.com
homepage: https://github.com/Frezyx/bottom_bar_with_sheet

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ">=4.3.2+2 <4.4.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0


flutter:

